framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection:
        enabled: true
    session:
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/prod'
        cookie_secure: auto
        cookie_samesite: lax
        gc_maxlifetime: 1800
        gc_probability: 1
        gc_divisor: 100
