symfonycasts_reset_password:
    request_password_repository: App\Repository\ResetPasswordRequestRepository
    lifetime: 3600    # 1 heure en secondes
    throttle_limit: 3600  # 1 heure entre les demandes